/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author davidperezarias
 */
public class VistaMenu extends javax.swing.JFrame {

    VistaGestorCandidato vistaCandidato;
    VistaRegistroVotantes vistaVotante;
 
    
    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
        
        this.vistaCandidato = new VistaGestorCandidato(this);
        this.vistaVotante = new VistaRegistroVotantes(this);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonGestorCandidato = new javax.swing.JButton();
        Votante = new javax.swing.JButton();
        Eleccion = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO A LAS ELECCIONES");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(17, 19, 400, 34);

        botonGestorCandidato.setBackground(new java.awt.Color(153, 153, 255));
        botonGestorCandidato.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        botonGestorCandidato.setForeground(new java.awt.Color(255, 255, 255));
        botonGestorCandidato.setText("Gestor candidato");
        botonGestorCandidato.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonGestorCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestorCandidatoActionPerformed(evt);
            }
        });
        jPanel1.add(botonGestorCandidato);
        botonGestorCandidato.setBounds(40, 90, 170, 47);

        Votante.setBackground(new java.awt.Color(153, 153, 255));
        Votante.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Votante.setForeground(new java.awt.Color(255, 255, 255));
        Votante.setText("Registro votante");
        Votante.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Votante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VotanteActionPerformed(evt);
            }
        });
        jPanel1.add(Votante);
        Votante.setBounds(40, 160, 170, 47);

        Eleccion.setBackground(new java.awt.Color(153, 153, 255));
        Eleccion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Eleccion.setForeground(new java.awt.Color(255, 255, 255));
        Eleccion.setText("Gestor Eleccion");
        Eleccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Eleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleccionActionPerformed(evt);
            }
        });
        jPanel1.add(Eleccion);
        Eleccion.setBounds(40, 230, 180, 45);

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\ferna\\Documents\\NetBeansProjects\\elecciones-g8-main\\src\\main\\java\\Capturas\\menu.jpg")); // NOI18N
        Fondo.setText("jLabel2");
        jPanel1.add(Fondo);
        Fondo.setBounds(0, 0, 610, 330);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGestorCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestorCandidatoActionPerformed
     
        this.setVisible(false);
        this.vistaCandidato.setVisible(true);
        
    }//GEN-LAST:event_botonGestorCandidatoActionPerformed

    private void VotanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VotanteActionPerformed
        this.setVisible(false);
        this.vistaVotante.setVisible(true);
    }//GEN-LAST:event_VotanteActionPerformed

    private void EleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleccionActionPerformed
     
    }//GEN-LAST:event_EleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eleccion;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Votante;
    private javax.swing.JButton botonGestorCandidato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
